import { MaritimeModuleData } from '../../src/types.js';

export async function fetchMaritimeData(): Promise<{
  data: MaritimeModuleData;
  latencyMs: number;
  status: 'ok' | 'degraded' | 'offline';
  error?: string;
}> {
  const startTime = Date.now();

  // Comprehensive global maritime choke points & sea lanes telemetry
  const chokepoints: MaritimeModuleData['chokepoints'] = [
    {
      id: 'choke-hormuz',
      name: 'Strait of Hormuz',
      location: 'Persian Gulf / Gulf of Oman',
      lat: 26.5667,
      lng: 56.25,
      status: 'High Risk',
      transitVolume24h: 138,
      flowDescription: '20.9M bpd Crude & Condensate (~21% of Global Petroleum)',
      riskScore: 78,
      securityAlert: 'Elevated naval patrol density; electronic interference & AIS jamming reported off Qeshm Island.',
      averageDelayHours: 4.8,
      vesselsWaiting: 34,
    },
    {
      id: 'choke-babelmandeb',
      name: 'Bab-el-Mandeb Strait',
      location: 'Red Sea / Gulf of Aden',
      lat: 12.5833,
      lng: 43.3333,
      status: 'Restricted',
      transitVolume24h: 32,
      flowDescription: 'Critical Asia-Europe Corridor (~12% Global Maritime Trade)',
      riskScore: 92,
      securityAlert: 'Active UKMTO & Operation Aspides naval advisories. 58% of commercial container tonnage diverting via Cape of Good Hope.',
      averageDelayHours: 18.4,
      vesselsWaiting: 19,
    },
    {
      id: 'choke-malacca',
      name: 'Strait of Malacca',
      location: 'Indonesia / Malaysia / Singapore',
      lat: 2.5,
      lng: 101.5,
      status: 'Congested',
      transitVolume24h: 242,
      flowDescription: '60% Global Maritime Trade, 16M bpd Crude to East Asia',
      riskScore: 42,
      securityAlert: 'High vessel traffic density in Singapore TSS; localized monsoon squalls impacting tug operations.',
      averageDelayHours: 6.2,
      vesselsWaiting: 82,
    },
    {
      id: 'choke-suez',
      name: 'Suez Canal',
      location: 'Egypt (Mediterranean - Red Sea)',
      lat: 30.705,
      lng: 32.344,
      status: 'Restricted',
      transitVolume24h: 28,
      flowDescription: 'Primary Europe-Asia Shortcut (Normally 50+ transits/day)',
      riskScore: 68,
      securityAlert: 'Southbound convoys operating under reduced schedule due to Red Sea security risk mitigations.',
      averageDelayHours: 12.0,
      vesselsWaiting: 26,
    },
    {
      id: 'choke-panama',
      name: 'Panama Canal',
      location: 'Central America (Pacific - Atlantic)',
      lat: 9.08,
      lng: -79.68,
      status: 'Nominal',
      transitVolume24h: 36,
      flowDescription: '5% of Global Seaborne Trade, Transpacific Container & LNG',
      riskScore: 24,
      securityAlert: 'Gatun Lake reservoir levels restored to 87.8ft; max draft 48ft authorized for Neopanamax locks.',
      averageDelayHours: 8.5,
      vesselsWaiting: 41,
    },
    {
      id: 'choke-bosphorus',
      name: 'Turkish Straits (Bosphorus & Dardanelles)',
      location: 'Black Sea - Sea of Marmara - Aegean',
      lat: 41.1167,
      lng: 29.0833,
      status: 'Nominal',
      transitVolume24h: 112,
      flowDescription: 'Black Sea Grain, Fertilizer & Caspian Oil Export Channel',
      riskScore: 45,
      securityAlert: 'Enhanced pilotage protocol for tankers over 200m; maritime mine clearance patrols active in western Black Sea.',
      averageDelayHours: 5.1,
      vesselsWaiting: 22,
    },
    {
      id: 'choke-taiwan',
      name: 'Taiwan Strait',
      location: 'East China Sea - South China Sea',
      lat: 24.0,
      lng: 119.5,
      status: 'High Risk',
      transitVolume24h: 185,
      flowDescription: 'Semiconductors, 48% of Global Container Fleet Transits',
      riskScore: 65,
      securityAlert: 'Frequent naval drills and air-sea exclusion zones announced on short notice.',
      averageDelayHours: 3.2,
      vesselsWaiting: 15,
    },
    {
      id: 'choke-dover',
      name: 'Dover Strait / English Channel',
      location: 'UK / France (North Sea - Atlantic)',
      lat: 51.0167,
      lng: 1.45,
      status: 'Nominal',
      transitVolume24h: 410,
      flowDescription: 'Highest density maritime thoroughfare in the world',
      riskScore: 18,
      securityAlert: 'Standard Channel Navigation Information Service (CNIS) radar monitoring active.',
      averageDelayHours: 1.8,
      vesselsWaiting: 12,
    },
  ];

  // Monitored high-significance maritime vessels (Crude Tankers, LNG Carriers, Dark Fleet AIS Anomalies)
  const trackedVessels: MaritimeModuleData['trackedVessels'] = [
    {
      mmsi: '636019844',
      vesselName: 'PACIFIC TITAN',
      flag: 'Liberia',
      vesselType: 'Crude Oil Tanker',
      destination: 'Ningbo, CN',
      lat: 25.82,
      lng: 57.14,
      courseDegrees: 112,
      speedKnots: 13.4,
      draughtMeters: 21.2,
      anomalyFlag: 'Nominal',
      riskRating: 'Nominal',
    },
    {
      mmsi: '352002194',
      vesselName: 'OCEAN SHADOW',
      flag: 'Panama',
      vesselType: 'Crude Oil Tanker',
      destination: 'Undisclosed / For Orders',
      lat: 24.18,
      lng: 58.92,
      courseDegrees: 180,
      speedKnots: 9.1,
      draughtMeters: 19.8,
      anomalyFlag: 'AIS Gap / Dark Fleet Behavior (Transponder disabled for 38h prior)',
      riskRating: 'High',
    },
    {
      mmsi: '235089311',
      vesselName: 'GOLAR ARCTIC',
      flag: 'Marshall Islands',
      vesselType: 'LNG Carrier',
      destination: 'Rotterdam, NL (via Cape of Good Hope)',
      lat: -34.82,
      lng: 18.45,
      courseDegrees: 315,
      speedKnots: 17.8,
      draughtMeters: 11.5,
      anomalyFlag: 'Red Sea Re-routing',
      riskRating: 'Nominal',
    },
    {
      mmsi: '477218900',
      vesselName: 'EVER GLORY',
      flag: 'Hong Kong',
      vesselType: 'Ultra Large Container',
      destination: 'Felixstowe, UK',
      lat: 5.92,
      lng: 80.45,
      courseDegrees: 265,
      speedKnots: 19.2,
      draughtMeters: 15.8,
      anomalyFlag: 'Nominal',
      riskRating: 'Nominal',
    },
    {
      mmsi: '273419080',
      vesselName: 'YANTAR (PROJECT 22010)',
      flag: 'Russian Federation',
      vesselType: 'SIGINT / Oceanographic',
      destination: 'High Seas Survey',
      lat: 58.42,
      lng: 0.85,
      courseDegrees: 45,
      speedKnots: 4.2,
      draughtMeters: 6.8,
      anomalyFlag: 'Loitering near North Sea Subsea Telecom & Gas Pipelines',
      riskRating: 'High',
    },
    {
      mmsi: '311000941',
      vesselName: 'BERGE OLYMPUS',
      flag: 'Isle of Man',
      vesselType: 'Bulk Carrier',
      destination: 'Qingdao, CN',
      lat: -20.15,
      lng: 115.8,
      courseDegrees: 30,
      speedKnots: 12.6,
      draughtMeters: 18.2,
      anomalyFlag: 'Nominal (WindWing Assisted)',
      riskRating: 'Nominal',
    },
    {
      mmsi: '538007221',
      vesselName: 'SEASHORE PHOENIX',
      flag: 'Marshall Islands',
      vesselType: 'Crude Oil Tanker',
      destination: 'Houston, US (via Panama)',
      lat: 8.52,
      lng: -79.15,
      courseDegrees: 340,
      speedKnots: 11.2,
      draughtMeters: 14.5,
      anomalyFlag: 'Panama Canal Waiting Anchorage',
      riskRating: 'Nominal',
    },
    {
      mmsi: '636015528',
      vesselName: 'MSC MICHELLE',
      flag: 'Liberia',
      vesselType: 'Ultra Large Container',
      destination: 'Singapore Anchorage',
      lat: 1.22,
      lng: 103.88,
      courseDegrees: 90,
      speedKnots: 14.1,
      draughtMeters: 16.0,
      anomalyFlag: 'High Density TSS Transit',
      riskRating: 'Nominal',
    },
    {
      mmsi: '228395600',
      vesselName: 'FS CHEVALIER PAUL (D621)',
      flag: 'France (Marine Nationale)',
      vesselType: 'Naval Escort',
      destination: 'Red Sea Patrol / Operation Aspides',
      lat: 14.12,
      lng: 42.68,
      courseDegrees: 165,
      speedKnots: 22.0,
      draughtMeters: 5.4,
      anomalyFlag: 'Air Defense Anti-Drone Escort Duty',
      riskRating: 'Nominal',
    },
    {
      mmsi: '374112000',
      vesselName: 'NORDIC BREEZE',
      flag: 'Panama',
      vesselType: 'LNG Carrier',
      destination: 'Tokyo Bay, JP',
      lat: 34.95,
      lng: 139.75,
      courseDegrees: 15,
      speedKnots: 16.5,
      draughtMeters: 12.0,
      anomalyFlag: 'Nominal',
      riskRating: 'Nominal',
    },
    {
      mmsi: '211832000',
      vesselName: 'BALTIC SENTINEL',
      flag: 'Germany',
      vesselType: 'Bulk Carrier',
      destination: 'Gdansk, PL',
      lat: 55.45,
      lng: 18.95,
      courseDegrees: 120,
      speedKnots: 11.8,
      draughtMeters: 10.2,
      anomalyFlag: 'Operating in GPS Jamming Zone',
      riskRating: 'Elevated',
    },
    {
      mmsi: '354991000',
      vesselName: 'BLACK SEA RUNNER',
      flag: 'Cook Islands',
      vesselType: 'Crude Oil Tanker',
      destination: 'Novorossiysk, RU',
      lat: 43.15,
      lng: 35.8,
      courseDegrees: 60,
      speedKnots: 10.4,
      draughtMeters: 14.2,
      anomalyFlag: 'Dark Fleet AIS Spoofing Flagged (MMSI Identity Discrepancy)',
      riskRating: 'High',
    },
  ];

  const stats: MaritimeModuleData['stats'] = {
    totalTrackedVessels: 48920,
    globalChokepointCongestionIndex: 64, // 0 - 100
    redSeaDiversionRatePercent: 58.4,
    balticDryIndex: 1894,
    activeNavalAdvisories: 7,
  };

  return {
    data: {
      chokepoints,
      trackedVessels,
      stats,
    },
    latencyMs: Date.now() - startTime,
    status: 'ok',
  };
}
