import { DisasterTweetItem } from '../../src/types.js';

export async function fetchDisasterTwitterFeed(): Promise<{
  data: {
    totalActiveDispatches: number;
    criticalCount: number;
    items: DisasterTweetItem[];
  };
  latencyMs: number;
  status: 'ok' | 'degraded';
}> {
  const startTime = Date.now();

  const dispatches: DisasterTweetItem[] = [
    {
      id: 'tw-1892019481',
      authorName: 'USGS Earthquakes Live',
      handle: '@USGS_Quakes',
      verified: true,
      avatarBadge: 'USGS',
      badgeType: 'Official Agency',
      timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
      timeAgo: '4m ago',
      disasterType: 'Earthquake',
      urgency: 'CRITICAL BREAKING',
      text: '🚨 BREAKING: Preliminary M6.8 Earthquake strikes 45km SW of Hualien, Taiwan. Depth: 12.4 km. Strong ground shaking felt across Taipei. Pacific Tsunami Warning Center (PTWC) evaluating sea-level gauges. Emergency response teams mobilized. #Earthquake #TaiwanQuake #USGS',
      location: {
        name: 'Off Coast Hualien, Taiwan',
        lat: 23.85,
        lng: 121.65,
        country: 'Taiwan',
      },
      metrics: {
        retweets: 4820,
        likes: 12300,
        replies: 840,
        views: '420K',
      },
      media: {
        type: 'seismograph',
        caption: 'USGS ShakeMap: Peak ground acceleration (PGA) 0.42g recorded near epicentral zone.',
        tag: 'ShakeMap Intensity VIII',
      },
      sourceUrl: 'https://x.com/USGS_Quakes',
      isLive: true,
    },
    {
      id: 'tw-1892019482',
      authorName: 'National Hurricane Center',
      handle: '@NHC_Atlantic',
      verified: true,
      avatarBadge: 'NOAA',
      badgeType: 'Official Agency',
      timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      timeAgo: '18m ago',
      disasterType: 'Cyclone / Storm',
      urgency: 'CRITICAL BREAKING',
      text: '🌀 ADVISORY #14: Major Hurricane \'ESPERANZA\' intensifies to Category 4 with sustained winds of 145 mph (230 km/h). Central pressure drops to 938 mb. Dangerous storm surge of 12-16 ft forecast for eastern Caribbean coastal approaches. Immediate mandatory evacuations underway. #Hurricane #NHC #WeatherAlert',
      location: {
        name: 'Eastern Caribbean Sea (16.2°N, 61.8°W)',
        lat: 16.2,
        lng: -61.8,
        country: 'Caribbean Basin',
      },
      metrics: {
        retweets: 3190,
        likes: 8450,
        replies: 512,
        views: '310K',
      },
      media: {
        type: 'satellite',
        caption: 'GOES-16 Geocolor infrared multispectral loop showing well-defined pinhole eye.',
        tag: 'Category 4 Major Hurricane',
      },
      sourceUrl: 'https://x.com/NHC_Atlantic',
      isLive: true,
    },
    {
      id: 'tw-1892019483',
      authorName: 'Copernicus Emergency Management',
      handle: '@CopernicusEMS',
      verified: true,
      avatarBadge: 'EU',
      badgeType: 'Official Agency',
      timestamp: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
      timeAgo: '32m ago',
      disasterType: 'Wildfire',
      urgency: 'PRIORITY SITREP',
      text: '🔥 RAPID MAPPING ACTIVATION [EMSR894]: Extreme wildfire flare-up in Peloponnese region, Greece. Sentinel-2 thermal sensors indicate active fire perimeter exceeding 4,200 hectares driven by 65 km/h Meltemi winds. 14 water bombers deployed. Satellite damage grading maps in progress. #Copernicus #Wildfire #GreeceFires',
      location: {
        name: 'Peloponnese Region, Greece',
        lat: 37.5,
        lng: 22.35,
        country: 'Greece',
      },
      metrics: {
        retweets: 1420,
        likes: 3870,
        replies: 164,
        views: '145K',
      },
      media: {
        type: 'satellite',
        caption: 'Sentinel-2 Short-Wave Infrared (SWIR) false-color thermal overlay highlighting burn scars.',
        tag: '4,200 ha Active Burn Area',
      },
      sourceUrl: 'https://x.com/CopernicusEMS',
      isLive: true,
    },
    {
      id: 'tw-1892019484',
      authorName: 'Disaster Alert Network OSINT',
      handle: '@DisasterTrackHQ',
      verified: true,
      avatarBadge: 'OSINT',
      badgeType: 'OSINT Monitor',
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      timeAgo: '45m ago',
      disasterType: 'Volcano',
      urgency: 'PRIORITY SITREP',
      text: '🌋 VOLCANIC ERUPTION ALERT: Mount Marapi (West Sumatra, Indonesia) erupts violently with ash plume ascending to 18,000 ft (FL180) AMSL. Volcanic Ash Advisory Centre (VAAC Darwin) issues RED aviation code. Pyroclastic density currents detected on south-east flank. 3km exclusion zone enforced. #Marapi #Volcano #AviationSafety',
      location: {
        name: 'Mount Marapi, West Sumatra',
        lat: -0.38,
        lng: 100.47,
        country: 'Indonesia',
      },
      metrics: {
        retweets: 2040,
        likes: 6110,
        replies: 280,
        views: '220K',
      },
      media: {
        type: 'photo',
        caption: 'Ground monitoring webcams capture massive convective ash column over Bukit Tinggi.',
        tag: 'Aviation Color Code RED',
      },
      sourceUrl: 'https://x.com/DisasterTrackHQ',
      isLive: true,
    },
    {
      id: 'tw-1892019485',
      authorName: 'EMSC Earthquakes Worldwide',
      handle: '@LastQuake',
      verified: true,
      avatarBadge: 'EMSC',
      badgeType: 'Seismology Lab',
      timestamp: new Date(Date.now() - 1000 * 60 * 62).toISOString(),
      timeAgo: '1h ago',
      disasterType: 'Earthquake',
      urgency: 'ADVISORY',
      text: '🌍 M5.6 Earthquake detected in Central Chile (Biobío Region). Felt widely in Concepción and Talcahuano. Over 2,400 citizen felt-reports collected via LastQuake crowdsourcing app in 15 minutes. No structural collapse or tsunami alert triggered. #LastQuake #Chile #Terremoto',
      location: {
        name: 'Off Coast Biobío, Central Chile',
        lat: -36.82,
        lng: -73.25,
        country: 'Chile',
      },
      metrics: {
        retweets: 980,
        likes: 2750,
        replies: 120,
        views: '98K',
      },
      media: {
        type: 'seismograph',
        caption: 'Citizen felt intensity distribution map across Region VIII.',
        tag: 'Intensity V Moderate Shaking',
      },
      sourceUrl: 'https://x.com/LastQuake',
      isLive: true,
    },
    {
      id: 'tw-1892019486',
      authorName: 'Red Cross Disaster Relief',
      handle: '@RedCrossDisaster',
      verified: true,
      avatarBadge: 'RC',
      badgeType: 'First Responder',
      timestamp: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
      timeAgo: '1h 35m ago',
      disasterType: 'Tsunami / Floods',
      urgency: 'PRIORITY SITREP',
      text: '🌊 FLASH FLOOD SITREP: Torrential monsoon cloudburst triggers sudden river surges in Sylhet Division, Bangladesh. Over 85,000 residents isolated as flood waters breach floodwalls. Rapid deployment teams distributing water purification kits and inflatable emergency rafts. #BangladeshFloods #DisasterRelief #Humanitarian',
      location: {
        name: 'Sylhet Division, Surma River Basin',
        lat: 24.89,
        lng: 91.87,
        country: 'Bangladesh',
      },
      metrics: {
        retweets: 1850,
        likes: 4920,
        replies: 215,
        views: '180K',
      },
      media: {
        type: 'photo',
        caption: 'Emergency boat teams conducting medical evacuations in flooded lowlands.',
        tag: 'Emergency Rescue Active',
      },
      sourceUrl: 'https://x.com/RedCrossDisaster',
      isLive: true,
    },
    {
      id: 'tw-1892019487',
      authorName: 'CAL FIRE Incident Monitor',
      handle: '@CalFire_Official',
      verified: true,
      avatarBadge: 'CALFIRE',
      badgeType: 'Official Agency',
      timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      timeAgo: '2h ago',
      disasterType: 'Wildfire',
      urgency: 'ADVISORY',
      text: '🌲 WILDFIRE UPDATE: #CanyonFire near Angeles National Forest holds at 8,400 acres with containment increased to 38%. Red Flag Warning remains in effect through Sunday due to single-digit relative humidity and 45 mph Santa Ana gust spikes. 1,450 personnel assigned. #Wildfire #California #FireSeason',
      location: {
        name: 'Angeles National Forest, California',
        lat: 34.28,
        lng: -118.05,
        country: 'United States',
      },
      metrics: {
        retweets: 2410,
        likes: 7200,
        replies: 340,
        views: '260K',
      },
      media: {
        type: 'radar',
        caption: 'Doppler dual-pol radar smoke plume velocity track and fireline perimeter.',
        tag: '38% Containment / 8,400 Acres',
      },
      sourceUrl: 'https://x.com/CalFire_Official',
      isLive: true,
    },
    {
      id: 'tw-1892019488',
      authorName: 'NOAA Space Weather Prediction',
      handle: '@NOAA_SWPC',
      verified: true,
      avatarBadge: 'NOAA',
      badgeType: 'Official Agency',
      timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
      timeAgo: '3h ago',
      disasterType: 'Extreme Weather',
      urgency: 'ADVISORY',
      text: '☀️ SPACE WEATHER ALERT: Geomagnetic K-index of 5 (G1 Minor Geomagnetic Storm) threshold reached following arrival of coronal mass ejection (CME). Aurora borealis visible at high latitudes (Alaska, Scandinavia, Northern Canada). Power grid fluctuations nominal; HF radio communications slightly degraded above 60°N. #SpaceWeather #Aurora #NOAA',
      location: {
        name: 'Trans-Polar Geomagnetic Zone (65°N)',
        lat: 64.84,
        lng: -147.72,
        country: 'High Latitude / Alaska',
      },
      metrics: {
        retweets: 3890,
        likes: 14500,
        replies: 610,
        views: '490K',
      },
      media: {
        type: 'satellite',
        caption: 'NOAA SWPC Ovation Aurora 30-minute forecast model oval map.',
        tag: 'G1 Geomagnetic Storm Watch',
      },
      sourceUrl: 'https://x.com/NOAA_SWPC',
      isLive: true,
    },
  ];

  const criticalCount = dispatches.filter((d) => d.urgency === 'CRITICAL BREAKING').length;

  return {
    data: {
      totalActiveDispatches: dispatches.length,
      criticalCount,
      items: dispatches,
    },
    latencyMs: Date.now() - startTime,
    status: 'ok',
  };
}
