import { SweepPayload } from '../types.js';

export function exportSweepAsJson(sweep: SweepPayload) {
  const blob = new Blob([JSON.stringify(sweep, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `miz-intelligence-${sweep.sweepId}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportSweepAsMarkdown(sweep: SweepPayload) {
  const md = `# MIZ PERSONAL INTELLIGENCE REPORT
**Sweep ID:** ${sweep.sweepId}
**Timestamp:** ${sweep.timestamp}
**Overall Status:** ${sweep.overallStatus}
**Sweep Duration:** ${sweep.sweepDurationMs}ms

---

## 1. EXECUTIVE SITUATION BRIEFING
**Threat Posture:** ${sweep.synthesis?.threatLevel || 'ELEVATED'}
${sweep.synthesis?.executiveBrief || 'Telemetry synchronized across all connected OSINT endpoints.'}

### Key Strategic Findings:
${sweep.synthesis?.keyFindings.map((f) => `- ${f}`).join('\n') || '- All parameters nominal.'}

---

## 2. ACTIVE ANOMALIES & ALERTS (${sweep.alerts.length})
- **🔴 FLASH Alerts:** ${sweep.delta.flashCount}
- **🟡 PRIORITY Alerts:** ${sweep.delta.priorityCount}
- **🔵 ROUTINE Briefings:** ${sweep.delta.routineCount}

### Alert Digest:
${sweep.alerts.map((a) => `### [${a.tier}] ${a.title}
*Domain:* ${a.domain.toUpperCase()} | *Time:* ${a.timestamp}
${a.summary}
${a.metrics ? Object.entries(a.metrics).map(([k, v]) => `  - **${k}:** ${v}`).join('\n') : ''}
`).join('\n')}

---

## 3. GEOSPATIAL & SPACE WEATHER
- **USGS Earthquakes:** ${sweep.geospatial.data.earthquakes.totalCount} total (Max M${sweep.geospatial.data.earthquakes.maxMag.toFixed(1)}, ${sweep.geospatial.data.earthquakes.significantCount} >= M4.5)
- **NOAA Space Weather:** Planetary Kp ${sweep.geospatial.data.spaceWeather.kpCurrent} (${sweep.geospatial.data.spaceWeather.stormLevel})
- **NASA Thermal Hotspots:** ${sweep.geospatial.data.thermalAnomalies.totalHotspots} (${sweep.geospatial.data.thermalAnomalies.highConfidenceCount} high-confidence)

---

## 4. MARKETS & MACRO TELEMETRY
- **Dominant Trend:** ${sweep.markets.data.marketStatus.dominantTrend}
- **10Y-2Y Yield Curve Spread:** ${sweep.markets.data.marketStatus.spread10Y2Y}% (${sweep.markets.data.marketStatus.yieldCurveInversion ? 'INVERTED' : 'NORMALIZED'})
- **Key Tickers:**
${sweep.markets.data.tickers.map((t) => `  - **${t.symbol} (${t.name}):** ${t.price.toLocaleString()} ${t.unit || ''} (${t.change24h > 0 ? '+' : ''}${t.change24h}%)`).join('\n')}

---

## 5. PUBLIC HEALTH & BIO-RESEARCH
- **Bio-Risk Index:** ${sweep.health.data.bioRiskIndex}/100
- **High-Impact Literature:**
${sweep.health.data.papers.slice(0, 5).map((p) => `  - *${p.title}* (${p.journal}, ${p.pubDate}) [${p.threatLevel}]`).join('\n')}

---

## 6. INFRASTRUCTURE & CYBER OSINT
- **CISA KEV Catalog Count:** ${sweep.infrastructure.data.cisaKev.totalCatalogCount} (${sweep.infrastructure.data.cisaKev.ransomwareTargetedCount} ransomware-weaponized)
- **Tracked Aircraft:** ${sweep.infrastructure.data.airTraffic.totalTrackedAircraft} (${sweep.infrastructure.data.airTraffic.emergencySquawks.length} emergency squawks)

---

## 7. ACTIONABLE TRADE & HEDGE HYPOTHESES
${sweep.synthesis?.tradeAndHedgeHypotheses.map((h) => `### ${h.title}
*Timeframe:* ${h.timeframe} | *Risk:* ${h.riskLevel}
**Thesis:** ${h.thesis}
**Target Assets:** ${h.affectedAssets.join(', ')}
`).join('\n') || 'No speculative trade hypotheses generated.'}

*Generated by Miz Intelligence Sweep Engine.*
`;

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `miz-briefing-${sweep.sweepId}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
