import { SweepPayload } from '../types.js';

export function exportSweepAsJson(sweep: SweepPayload) {
  const blob = new Blob([JSON.stringify(sweep, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `milz-sentry-intelligence-${sweep.sweepId}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportSweepAsMarkdown(sweep: SweepPayload) {
  const md = `# MILZ SENTRY PERSONAL INTELLIGENCE REPORT
**Sweep ID:** ${sweep.sweepId}
**Timestamp:** ${sweep.timestamp}
**Overall Status:** ${sweep.overallStatus}
**Sweep Duration:** ${sweep.sweepDurationMs}ms

---

## 1. EXECUTIVE SITUATION BRIEFING
**Threat Posture:** ${sweep.synthesis?.threatLevel || 'ELEVATED'}
${sweep.synthesis?.executiveBrief || 'Telemetry synchronized across all connected OSINT endpoints.'}

### Key Strategic Findings:
${sweep.synthesis?.keyFindings.map((f) => `- ${f}`).join('\n') || '- All parameters nominal.'}

---

## 2. ACTIVE ANOMALIES & ALERTS (${sweep.alerts.length})
- **🔴 FLASH Alerts:** ${sweep.delta.flashCount}
- **🟡 PRIORITY Alerts:** ${sweep.delta.priorityCount}
- **🔵 ROUTINE Briefings:** ${sweep.delta.routineCount}

### Alert Digest:
${sweep.alerts.map((a) => `### [${a.tier}] ${a.title}
*Domain:* ${a.domain.toUpperCase()} | *Time:* ${a.timestamp}
${a.summary}
${a.metrics ? Object.entries(a.metrics).map(([k, v]) => `  - **${k}:** ${v}`).join('\n') : ''}
`).join('\n')}

---

## 3. GEOSPATIAL & SPACE WEATHER
- **USGS Earthquakes:** ${sweep.geospatial.data.earthquakes.totalCount} total (Max M${sweep.geospatial.data.earthquakes.maxMag.toFixed(1)}, ${sweep.geospatial.data.earthquakes.significantCount} >= M4.5)
- **NOAA Space Weather:** Planetary Kp ${sweep.geospatial.data.spaceWeather.kpCurrent} (${sweep.geospatial.data.spaceWeather.stormLevel})
- **NASA Thermal Hotspots:** ${sweep.geospatial.data.thermalAnomalies?.totalHotspots || 0} (${sweep.geospatial.data.thermalAnomalies?.highConfidenceCount || 0} high-confidence)

---

## 4. MARKETS & MACRO TELEMETRY
- **Dominant Trend:** ${sweep.markets.data.marketStatus.dominantTrend}
- **10Y-2Y Yield Curve Spread:** ${sweep.markets.data.marketStatus.spread10Y2Y}% (${sweep.markets.data.marketStatus.yieldCurveInversion ? 'INVERTED' : 'NORMALIZED'})
- **Key Tickers:**
${sweep.markets.data.tickers.map((t) => `  - **${t.symbol} (${t.name}):** ${t.price.toLocaleString()} ${t.unit || ''} (${t.change24h > 0 ? '+' : ''}${t.change24h}%)`).join('\n')}

---

## 5. PUBLIC HEALTH & BIO-RESEARCH
- **Bio-Risk Index:** ${sweep.health.data.bioRiskIndex}/100
- **High-Impact Literature:**
${sweep.health.data.papers.slice(0, 5).map((p) => `  - *${p.title}* (${p.journal}, ${p.pubDate}) [${p.threatLevel}]`).join('\n')}

---

## 6. INFRASTRUCTURE & CYBER OSINT
- **CISA KEV Catalog Count:** ${sweep.infrastructure.data.cisaKev.totalCatalogCount} (${sweep.infrastructure.data.cisaKev.ransomwareTargetedCount} ransomware-weaponized)
- **Tracked Aircraft:** ${sweep.infrastructure.data.airTraffic.totalTrackedAircraft} (${sweep.infrastructure.data.airTraffic.emergencySquawks.length} emergency squawks)

---

## 7. ACTIONABLE TRADE & HEDGE HYPOTHESES
${sweep.synthesis?.tradeAndHedgeHypotheses.map((h) => `### ${h.title}
*Timeframe:* ${h.timeframe} | *Risk:* ${h.riskLevel}
**Thesis:** ${h.thesis}
**Target Assets:** ${h.affectedAssets.join(', ')}
`).join('\n') || 'No speculative trade hypotheses generated.'}

*Generated by MILZ Sentry Intelligence Sweep Engine.*
`;

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `milz-sentry-briefing-${sweep.sweepId}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportSweepAsCsvByCategory(sweep: SweepPayload, category: string) {
  const rows: string[][] = [];
  
  if (category === 'alerts' || category === 'all') {
    rows.push(['Category', 'Alert ID', 'Tier', 'Domain', 'Title', 'Summary', 'Timestamp', 'Source URL']);
    sweep.alerts.forEach((alert) => {
      rows.push([
        'Alert',
        alert.id,
        alert.tier,
        alert.domain,
        alert.title,
        alert.summary,
        alert.timestamp,
        alert.sourceUrl || ''
      ]);
    });
  }
  
  if (category === 'geospatial' || category === 'all') {
    if (category !== 'all') {
      rows.push(['Category', 'Entity ID', 'Location/Place', 'Metric Value', 'Additional Details', 'Timestamp']);
    }
    // Earthquakes
    sweep.geospatial.data.earthquakes.items.forEach((eq) => {
      rows.push([
        'Geospatial - Earthquake',
        eq.id,
        eq.place,
        `M${eq.mag.toFixed(1)}`,
        `Depth: ${eq.coordinates[2]}km, Tsunami: ${eq.tsunami ? 'Yes' : 'No'}`,
        new Date(eq.time).toISOString()
      ]);
    });
    // Thermal/Fires
    const fireAnomalies = sweep.geospatial.data.thermalAnomalies?.items || sweep.geospatial.data.fireAnomalies || [];
    fireAnomalies.forEach((fire) => {
      rows.push([
        'Geospatial - Wildfire',
        fire.id,
        fire.region,
        `FRP: ${fire.frp} MW`,
        `Brightness: ${fire.brightness}K, Confidence: ${fire.confidence}`,
        fire.acqDate
      ]);
    });
    // Disaster Feed
    sweep.geospatial.data.disasterFeed?.items.forEach((tweet) => {
      rows.push([
        'Geospatial - OSINT Dispatch',
        tweet.id,
        tweet.location?.name || '',
        tweet.disasterType,
        tweet.text,
        tweet.timestamp
      ]);
    });
  }

  if (category === 'markets' || category === 'all') {
    if (category !== 'all') {
      rows.push(['Category', 'Symbol', 'Name', 'Price', '24h Change', 'Description/Metrics']);
    }
    sweep.markets.data.tickers.forEach((ticker) => {
      rows.push([
        'Markets - Ticker',
        ticker.symbol,
        ticker.name,
        ticker.price.toString(),
        `${ticker.change24h}%`,
        ticker.volume24h ? `Vol: ${ticker.volume24h}` : ''
      ]);
    });
    sweep.markets.data.macro.forEach((m) => {
      rows.push([
        'Markets - Macro Indicator',
        m.code,
        m.name,
        m.value.toString(),
        m.trend,
        m.description
      ]);
    });
  }

  if (category === 'infrastructure' || category === 'all') {
    if (category !== 'all') {
      rows.push(['Category', 'ID/MMSI/ICAO', 'System / Asset Name', 'Status / Squawk', 'Detailed Description', 'Timestamp']);
    }
    // CISA KEV
    sweep.infrastructure.data.cisaKev.recentAdded.forEach((kev) => {
      rows.push([
        'Infrastructure - CISA KEV',
        kev.cveID,
        `${kev.vendorProject} ${kev.product}`,
        kev.knownRansomwareCampaignUse === 'Known' ? 'Ransomware Tracked' : 'Nominal Vuln',
        kev.shortDescription,
        kev.dateAdded
      ]);
    });
    // Flights
    sweep.infrastructure.data.airTraffic.emergencySquawks.forEach((f) => {
      rows.push([
        'Infrastructure - Flight Squawk',
        f.icao24,
        `${f.callsign} (${f.aircraftType || 'AIRCRAFT'})`,
        f.squawkType,
        `Altitude: ${f.altitudeFt}ft, Velocity: ${f.velocityKnots}kts, Heading: ${f.heading}°`,
        f.lastContact
      ]);
    });
    // Vessels
    sweep.infrastructure.data.maritime.trackedVessels.forEach((v) => {
      rows.push([
        'Infrastructure - Maritime Vessel',
        v.mmsi,
        v.vesselName,
        v.vesselType,
        `Flag: ${v.flag}, Speed: ${v.speedKnots}kts, Course: ${v.courseDegrees}°, Risk: ${v.riskRating}`,
        new Date().toISOString()
      ]);
    });
  }

  if (category === 'health' || category === 'all') {
    if (category !== 'all') {
      rows.push(['Category', 'ID / Pathogen', 'Source / Journal', 'Alert / Threat Level', 'Summary Details', 'Date']);
    }
    sweep.health.data.papers.forEach((p) => {
      rows.push([
        'Health - Paper',
        p.id,
        p.journal,
        p.threatLevel,
        p.title,
        p.pubDate
      ]);
    });
    sweep.health.data.outbreaks.forEach((o) => {
      rows.push([
        'Health - Outbreak',
        o.id,
        o.region,
        o.alertLevel,
        `${o.pathogen}: ${o.details}`,
        o.date
      ]);
    });
  }

  const csvContent = rows.map(e => e.map(val => `"${val.replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.setAttribute('href', url);
  a.setAttribute('download', `milz-sentry-${category}-data-${sweep.sweepId}.csv`);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportSweepAsPdf(sweep: SweepPayload) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export PDF reports');
    return;
  }

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>MILZ Sentry - Operational Intelligence Briefing Report</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          color: #111;
          background: #fff;
          margin: 40px;
          line-height: 1.5;
        }
        .header {
          border-bottom: 3px double #111;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .header h1 {
          font-size: 26px;
          text-transform: uppercase;
          margin: 0 0 10px 0;
          letter-spacing: 2px;
        }
        .meta-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 15px;
          font-size: 11px;
          text-transform: uppercase;
          font-family: monospace;
          background: #f4f4f4;
          padding: 10px;
          border: 1px solid #ddd;
        }
        h2 {
          font-size: 16px;
          border-bottom: 1px solid #111;
          padding-bottom: 5px;
          margin-top: 30px;
          text-transform: uppercase;
          letter-spacing: 1px;
        }
        h3 {
          font-size: 13px;
          margin: 15px 0 5px 0;
          text-transform: uppercase;
        }
        p {
          font-size: 12px;
          margin: 5px 0 15px 0;
        }
        .alert-card {
          border-left: 4px solid #111;
          padding-left: 15px;
          margin: 15px 0;
        }
        .alert-card.flash {
          border-left-color: #ef4444;
          background: #fef2f2;
          padding: 8px 12px;
        }
        .alert-card.priority {
          border-left-color: #f59e0b;
          background: #fefbeb;
          padding: 8px 12px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 15px 0;
          font-size: 11px;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 6px 8px;
          text-align: left;
        }
        th {
          background-color: #f2f2f2;
          font-weight: bold;
        }
        .footer {
          margin-top: 50px;
          border-top: 1px solid #ddd;
          padding-top: 15px;
          font-size: 10px;
          text-align: center;
          color: #777;
        }
        @media print {
          body { margin: 20px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="no-print" style="background: #111; color: white; padding: 12px; text-align: center; font-family: sans-serif; font-weight: bold; margin-bottom: 20px; border-radius: 4px; display: flex; justify-content: center; align-items: center; gap: 15px;">
        <span>📄 Intelligence Briefing Compiled. Click "Print / Save to PDF" in your system dialog.</span>
        <button onclick="window.print()" style="padding: 6px 14px; border: none; background: #00ff41; color: black; font-weight: bold; cursor: pointer; border-radius: 3px; font-family: monospace;">Print Report</button>
      </div>

      <div class="header">
        <h1>MILZ Sentry Intelligence Briefing</h1>
        <div style="font-size: 13px; font-weight: bold; text-transform: uppercase; margin-bottom: 12px; color: #555;">Official Operational Situation sitrep Report</div>
        <div class="meta-grid">
          <div><strong>Node ID:</strong> MS-SENTRY-${sweep.sweepId.slice(0, 10)}</div>
          <div><strong>Compiled At:</strong> ${new Date(sweep.timestamp).toUTCString()}</div>
          <div><strong>Overall Threat Posture:</strong> ${sweep.synthesis?.threatLevel || 'ELEVATED'}</div>
        </div>
      </div>

      <h2>1. Executive Situation Summary</h2>
      <p style="font-size: 13px; font-weight: bold; line-height: 1.6;">
        ${sweep.synthesis?.executiveBrief || 'Real-time telemetry feeds are nominal. Cross-domain correlations compiled across connected satellite GIS endpoints and macroeconomic monitors.'}
      </p>

      <h3>Key Strategic Intelligence Findings</h3>
      <ul>
        ${sweep.synthesis?.keyFindings.map(f => `<li style="font-size: 12px; margin-bottom: 5px;">${f}</li>`).join('') || '<li>No active critical anomalies registered in the current sweep.</li>'}
      </ul>

      <h2>2. Active Operational Alerts (${sweep.alerts.length} Vectors)</h2>
      ${sweep.alerts.map(alert => `
        <div class="alert-card ${alert.tier === 'FLASH' ? 'flash' : alert.tier === 'PRIORITY' ? 'priority' : ''}">
          <div style="font-weight: bold; font-family: monospace; font-size: 10px;">
            [${alert.tier}] [${alert.domain.toUpperCase()}] &bull; ${alert.timestamp}
          </div>
          <div style="font-weight: bold; font-size: 13px; margin: 3px 0;">${alert.title}</div>
          <p style="margin: 0;">${alert.summary}</p>
        </div>
      `).join('')}

      <h2>3. Geospatial & Space Weather Telemetry</h2>
      <table>
        <thead>
          <tr>
            <th>Event Category</th>
            <th>Location / Region</th>
            <th>Magnitude / Severity</th>
            <th>Impact Details</th>
          </tr>
        </thead>
        <tbody>
          ${sweep.geospatial.data.earthquakes.items.map(eq => `
            <tr>
              <td>USGS Seismological Event</td>
              <td>${eq.place}</td>
              <td>M${eq.mag.toFixed(1)}</td>
              <td>Depth: ${eq.coordinates[2]}km, Tsunami Hazard: ${eq.tsunami ? 'YES' : 'NO'}</td>
            </tr>
          `).join('')}
          ${(sweep.geospatial.data.thermalAnomalies?.items || sweep.geospatial.data.fireAnomalies || []).slice(0, 8).map(fire => `
            <tr>
              <td>Thermal Hotspot (NASA FIRMS)</td>
              <td>${fire.region}</td>
              <td>FRP ${fire.frp} MW</td>
              <td>Confidence: ${fire.confidence}, Brightness: ${fire.brightness}K</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <h2>4. Infrastructure & Maritime OSINT Desk</h2>
      <table>
        <thead>
          <tr>
            <th>Asset / Target ID</th>
            <th>Operating Flag / Nation</th>
            <th>Identified Threat Status</th>
            <th>Telemetry / Last Seen</th>
          </tr>
        </thead>
        <tbody>
          ${sweep.infrastructure.data.airTraffic.emergencySquawks.map(f => `
            <tr>
              <td>Flight ADS-B: ${f.callsign}</td>
              <td>Origin: ${f.originCountry}</td>
              <td>Squawk: ${f.squawk} (${f.squawkType})</td>
              <td>Alt: ${f.altitudeFt || 'N/A'} ft, Spd: ${f.velocityKnots || 'N/A'} kts</td>
            </tr>
          `).join('')}
          ${sweep.infrastructure.data.maritime.trackedVessels.map(v => `
            <tr>
              <td>Vessel AIS: ${v.vesselName} (${v.vesselType})</td>
              <td>Flag: ${v.flag}</td>
              <td>Risk Rating: ${v.riskRating}</td>
              <td>Anomaly: ${v.anomalyFlag || 'Nominal'}, Speed: ${v.speedKnots} kts</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <h2>5. Macroeconomic & Volatility Indicators</h2>
      <table>
        <thead>
          <tr>
            <th>Ticker Symbol</th>
            <th>Instrument Name</th>
            <th>Latest Quote</th>
            <th>24-Hour Change</th>
          </tr>
        </thead>
        <tbody>
          ${sweep.markets.data.tickers.map(ticker => `
            <tr>
              <td><strong>${ticker.symbol}</strong></td>
              <td>${ticker.name}</td>
              <td>${ticker.price.toLocaleString()} ${ticker.unit || ''}</td>
              <td style="color: ${ticker.change24h < 0 ? '#b91c1c' : '#15803d'}; font-weight: bold;">
                ${ticker.change24h > 0 ? '+' : ''}${ticker.change24h}%
              </td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="footer">
        MILZ Sentry &bull; Cryptosecure Intelligence Feed &bull; Dispatched via Secure SSL Client Socket.
      </div>
      <script>
        window.onload = function() {
          setTimeout(function() { window.print(); }, 600);
        }
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}

